package presets

import "github.com/olivierh59500/democonstructionkit/motion"

// NonamenoGlyphPages reproduces the authored 20-by-8 page choreography while
// leaving page text and the starting delay pattern to the screen. Its three
// delay maps are generated by reusable grid patterns. The spiral's repeated
// step 138 is retained because it is present in the original choreography.
func NonamenoGlyphPages(pages []string, initialPattern int) (motion.GlyphPageConfig, error) {
	serpentine, err := motion.SerpentineGlyphDelays(20, 8)
	if err != nil {
		return motion.GlyphPageConfig{}, err
	}
	columns, err := motion.MirroredColumnGlyphDelays(20, 8)
	if err != nil {
		return motion.GlyphPageConfig{}, err
	}
	spiral, err := motion.SpiralGlyphDelays(20, 8)
	if err != nil {
		return motion.GlyphPageConfig{}, err
	}
	spiral[3*20+10] = 138
	return motion.GlyphPageConfig{
		Pages: pages, DelayPatterns: [][]int{serpentine, columns, spiral}, Columns: 20,
		Origin:     motion.GlyphPoint{X: 16, Y: 160, Z: 1},
		Center:     motion.GlyphPoint{X: 320, Y: 240, Z: 1e-9},
		ColumnStep: 32, RowStep: 32,
		EnterDurationMS: 2000, ExitDurationMS: 1000, DelayStepMS: 40,
		EnterEase: motion.ElasticOut, ExitEase: motion.ElasticIn,
		InitialPattern: initialPattern,
	}, nil
}
